package com.example.backend.models;

import org.springframework.boot.autoconfigure.domain.EntityScan;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@Entity
@Table(name = "Products")
public class Product {

    @Id
    //This annotation marks the field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // this annotation just specifies how the primary key should be generated. then GenerationType.IDENTITY indicates
    // that the primary key should be automatically generated by the underlying database.

    private Long id;

    private String name;
    private String description;
    private double price;
    private String category;
    private String condition;
    private String sellerUsername;
    private Date datePosted;

    public Product() {
        // Default constructor
    }
    public Long getId() {
        return id;
    }

    public void setId (Long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description = description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getPrice() {
        return price;
    }
    public void setPrice (double price) {
        this.price = price;
    }

    public String getCategory() {
        return category;
    }
    public void setCategory() {
        this.category = category;
    }

    public String getCondition() {
        return condition;
    }
    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getSellerUsername () {
        return sellerUsername;
    }

    public void setSellerUsername(String sellerUsername) {
        this.sellerUsername = sellerUsername;
    }

    public Date getDatePosted() {
        return datePosted;
    }

    public void setDatePosted(Date datePosted) {
        this.datePosted = datePosted;
    }
}
